CREATE TABLE IF NOT EXISTS files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name TEXT NOT NULL,
    download_url TEXT NOT NULL,
    upload_time INTEGER NOT NULL,
    size TEXT NOT NULL,
    file_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    token TEXT NOT NULL,
    target INTEGER NOT NULL,
    url INTEGER,
    pass TEXT
);